### PR TITLE
Collection & Search Results Views

### PR DESCRIPTION
**Pull request by sarahscott**
- [x] Setup/install
- [x] Collection view grid (desk, tab, mobile)
- [x] Collection view header (desk, tab, mobile)
- [x] Enforce 5:4 crop on product images in grid
- [x] Pagination (basic)
- [x] Cleanup boilerplate code
- [x] Search Results

A few questions:
- "20px gutter on desktop rather than 30" for the header or the collection results?
- Will there be product variants?
- On search results page when there aren't any results, where does 'Contact Us' link to?

### CODE REVIEW

**Comment by 1aurabrown** [comment]
Looks good!
Just some notes:

- 20px gutter on desktop rather than 30
- can we put a space between the strike-through text and the black text on the price?
- for square images: there is another snippet called 'responsive-image-only' which doesn't include the image wrapper element, only the image. you would put your own wrapper around it and style that element. OR you could modify the 'responsive-image' snippet to accept an optional aspect ratio variable to be used if provided, otherwise it will use the image's original aspect ratio, like it currently does.
- to use the grid in the search view: you can extract the grid into a snippet that accepts an array of products as a variable, then the snippet can be included in the collection view and the search view.
- i will modify the search form to only perform a search on products only (not pages or articles) : https://help.shopify.com/en/themes/liquid/objects/search#search-results

**Comment by sarahscott** [comment]
How do you wanna deal with pagination?

**Comment by 1aurabrown** [comment]
Will take a look, re: pagination there is some built in shopify stuff for this which should be  part of the boilerplate. See https://help.shopify.com/en/themes/liquid/objects/paginate

Just off the top of my head, I would paginate by 48 and make a custom pagination snippet for collections w more than one page, use the shopify liquid pagination object to generate the page display (this is in the designs)
https://help.shopify.com/en/themes/liquid/objects/part

It might even just work with the "default pagination" which I didn't know about til now: https://help.shopify.com/en/themes/liquid/filters/additional-filters#default_pagination just by passing in prev and next texts and adding a border radius + border on the currently selected page number

**Comment by 1aurabrown** [comment]
looks great! i just rebased this branch against my own changes, which i had merged into master, and re-pushed to this branch. will merge.

to answer your other questions:
**"20px gutter on desktop rather than 30" for the header or the collection results?**
- i meant between the collection/results grid items (i think there was something weird with the zeplin export that makes it hard to measure the distance between elements)
**Will there be product variants?**
- for the time being, no. some items like pillows and rugs may have multiple inventory and may later be reorganized to use variants, but most items are one-of-a-kind
**On search results page when there aren't any results, where does 'Contact Us' link to?**
- it can link to /pages/contact (which currently doesn't exist on this dev site), but maybe this whole text area can be a section 'richtext' field so that the client can modify the copy on the no results page and change the link if they want to.

**Comment by 1aurabrown** [comment]
One other note--there is a mixin and class for a fake underline which is a little lower than the regular one. I know it's pedantic but do you think you could use this on the Vendor text? What I do is make an inner element that gets the 'faux-underline' class, and then the line height of this inner element can be adjusted independent to get the correct spacing between the fake underline and the text without affecting the overall spacing of the text to other text elements above and below.

**Pull request merged**
